⟨formula⟩ ::= <atom> | <not> <formula> | "(" <formula> <and> <formula> ")" | "(" <formula> <or> <formula> ")" | "(" <formula> <if-then> <formula> ")" | "(" <formula> <iff> <formula> ")"
⟨not⟩ ::= "~"
⟨and⟩ ::= "&"
⟨or⟩ ::= "||"
⟨if-then⟩ ::= "->"
⟨iff⟩ ::= "<>"
<atom> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"